### ISSUE TITLE
ga4gh_dos_server hook will not package installed via `python setup.py install`

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-repository-service-schemas#147]
```
> ga4gh_dos_server
...
swagger_spec_validator.common.SwaggerValidationError: ("module 'jsonschema._validators' has no attribute 'properties_draft4'", AttributeError("module 'jsonschema._validators' has no attribute 'properties_draft4'",))
```

Python 3.6.3

**Comment by natanlao** [comment]
This bug causes `TestPackage.test_schema_validity` to fail, so no test is required to close this ticket. This is a regression.

**Comment by natanlao** [comment]
Travis is not picking up this bug

**Comment by natanlao** [comment]
On further investigation, this bug appears when the package is installed via `python setup.py install`, and not when installed via `pip install .` or `pip install ga4gh-dos-schemas`.

**Comment by natanlao** [comment]
Can reproduce this with `pip install .` on a dirty working copy

**Comment by natanlao** [comment]
Some configurations are installing `jsonschema==3.0.0a2` instead of `jsonschema==2.6.0`

**Comment by natanlao** [comment]
Some of our dependencies require `jsonschema>=2.5.3`, and I think through some pip dependency resolution business, sometimes `jsonschema>=3` gets installed. I think we can close this by specifying `jsonschema>=2,<3` in `setup_requires` but I'm not sure how to go about testing this since the issue seems particularly stochastic.

**Comment by natanlao** [comment]
Working on Python 2.7.14 with `jsonschema==3.0.0a2`

**Comment by natanlao** [comment]
There appear to be a lot of factors affecting this issue. I'll try and list all of them here:
* The issue likely stems from `jsonschema>=3` being installed instead of `jsonschema>=2,<3`. This introduces a breaking API change - specifically, `jsonschema._validators.properties_draft4` is not present in v3.x. 
* The issue occurs if the package is installed from source (either through `pip install .` or `python setup.py install`).
* Despite being mentioned above, running `ga4gh_dos_server` is not a reliable way of detecting the issue, I suspect due in part to the lazy-loading behavior of the built in Flask server.
  - Running `ga4gh_dos_server` will immediately result in a traceback in affected installations if the dependencies installing in `requirements.txt` are installed. (This conflicts with my lazy-loading theory.)
  - Running the unit tests (either with `nosetests` if the development requirements are installed or `python -m unittest discover python/` if they are not) is sufficient to detect this issue. (This explains the difficulty I had reproducing the issue above.)
* `jsonschema==3.0.0a2` is a pre-release version and is being installed because bravado-core and connexion both specify a jsonschema requirement with no upper bound (`jsonschema>=2.5.1` in both cases), which matches pre-release versions (see pypa/pip#4969).
* `jsonschema==3.0.0a2` was released on August 8th of this year, which explains why we are seeing this issue now, but does not explain why Travis tests are passing. I am still unsure why this issue is (apparently) not persistent.
* Installing `jsonschema==2.6.0` seems to correct the problem.

I believe the following changes should be made:
* `jsonschema==2.6.0` should be specified as a dependency in `setup.py`.
* The `swagger-spec-validator==2.3.1` dependency should be removed from `requirements.txt` as it is installed by other packages.

Long-term, we should make a point of pinning to exact versions to avoid problems like this in the future.

**Comment by natanlao** [comment]
Correction: we should make a point of specifying a lower and upper bound in listing dependencies. Pip will not install a pre-release version if an upper bound is specified
